### ISSUE TITLE
Can't build on MacOS after commit a667670

### ISSUE THREAD

**Issue by brunobord** [tidwall/pogocache#34]
Hello,

I don't know much about C and compilers, so, please correct me if I'm wrong. But apparently, I haven't been able to build pogocache on my Macbook because of this line:

https://github.com/tidwall/pogocache/blob/main/src/sys.c#L250

When running "make", it threw me this error:

```
cd src && /Library/Developer/CommandLineTools/usr/bin/make all
cc -Wall -Wextra -Werror -g -O3 -flto=auto    -c -o sys.o sys.c
sys.c:250:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
  250 | #if TARGET_OS_MAC || TARGET_OS_IOS
      |     ^
sys.c:250:22: error: 'TARGET_OS_IOS' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
  250 | #if TARGET_OS_MAC || TARGET_OS_IOS
      |                      ^
2 errors generated.
make[1]: *** [sys.o] Error 1
make: *** [all] Error 2
```

It looks like this line was introduced by the commit a667670, so I've tried to compile pogocache using a preview commit (84511ac) and it compiled just fine.

So I guess it's a regression, unfortunately.

**Comment by brunobord** [comment]
I confirm that it's solved. Thanks a lot for the quick fix!
